Repository rahulvemula/SE-leasingPortal, pull requests merged in 2022-04, with the labels that each got.

#152 Sprint3 rv
  client/leasing-portal/src/components/Properties.tsx
  client/leasing-portal/src/components/Property-Card.tsx
  client/leasing-portal/src/components/auth/Login.tsx
  client/leasing-portal/src/components/auth/Register.tsx
  client/leasing-portal/src/store/auth.ts
Labels: frontend

#160 Resolve build failure for dependencies
  server/go.mod
  server/go.sum
Labels: Backend

#173 Build failure fix
  server/cmd/main/easylease.db
  server/cmd/main/society_test.go
Labels: Backend

#174 Heroku deployment setup for UI
  client/leasing-portal/package.json
  client/leasing-portal/src/components/UploadImage/UploadImage.jsx
Labels: Backend

#193 feat:add T&C
  client/leasing-portal/src/App.tsx
  client/leasing-portal/src/pages/Listing.tsx
  client/leasing-portal/src/pages/Terms.tsx
Labels: frontend

#194 Changes for Sprint 4
  client/leasing-portal/cypress/integration/lease.spec.js
  client/leasing-portal/cypress/integration/support.spec.js
  client/leasing-portal/cypress/integration/user-login.spec.js
  client/leasing-portal/cypress/integration/user-registration.spec.js
  client/leasing-portal/src/App.tsx
  client/leasing-portal/src/components/Header.tsx
  client/leasing-portal/src/pages/Listing.tsx
  client/leasing-portal/src/pages/Support.tsx
Labels: testing, frontend

#196 Fixed About us page UI #195
  client/leasing-portal/src/components/AboutUs/AboutUs.css
  client/leasing-portal/src/components/AboutUs/AboutUs.tsx
Labels: bug

#204 About us fix
  client/leasing-portal/src/App.tsx
  client/leasing-portal/src/components/AboutUs/AboutUs.tsx
  client/leasing-portal/src/test/AboutUs.test.tsx
Labels: testing, frontend
