Repository rahulvemula/SE-leasingPortal, pull requests merged in 2022-03, with the labels that each got.

#105 Added AboutUs page code
  client/leasing-portal/package-lock.json
  client/leasing-portal/src/App.tsx
  client/leasing-portal/src/components/AboutUs/AboutUs.css
  client/leasing-portal/src/components/AboutUs/AboutUs.tsx
  client/leasing-portal/src/components/Footer.tsx
Labels: user-stories

#108 Added Sprint2.md and Screenshots folder
  Screenshots/GoLangUnitTests.png
  Sprint2.md
Labels: user-stories

#135 Add Society class CRUD operations APIs
  .gitignore
  server/go.mod
  server/pkg/controllers/society-controller.go
  server/pkg/models/society.go
  server/pkg/routes/society-routes.go
Labels: Backend, go-lang

#137 Contributing new commits from forked branch B1 to main branch
  server/pkg/controllers/listing-controller.go
  server/pkg/models/listing.go
Labels: Backend

#138 Added unit tests for Society service api
  .gitignore
  server/cmd/main/society_test.go
Labels: Backend, unit-tests

#148 Sprint3 changes
  client/leasing-portal/src/App.tsx
  client/leasing-portal/src/components/Property-Card.tsx
  client/leasing-portal/src/pages/ApptListing.tsx
  client/leasing-portal/src/pages/Listing.tsx
  client/leasing-portal/src/test/Footer.test.tsx
Labels: frontend
